#!/system/bin/sh
exec 2>&1

[ -r ./conf ] && set -a && . ./conf && set +a

if [ "${WAIT_DECRYPT:-1}" != "0" ]; then
    echo "🔄 检测存储解密状态..."
    if [ "$(getprop sys.user.0.ce_available)" != "true" ]; then
        echo "🔐 存储未解密，等待 10s 后退出服务..."
        sleep 10
        exit 1
    fi
    echo "✅ OK"
fi

exec chpst -u "${CHPST_USER:-shell:inet:sdcard_r:sdcard_rw}" \
    openlist server ${OPENLIST_ARGS:---data /storage/emulated/0/Android/openlist}
